;;   -*- lexical-binding: t; -*-
;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        selected-off
        ))

(setq mc/cmds-to-run-once
      '(
        delete-window
        handle-switch-frame
        helm-M-x
        helm-find-files
        helm-maybe-exit-minibuffer
        helm-mini
        ignore
        indent-region
        mouse-delete-window
        mouse-drag-mode-line
        mouse-select-window
        mouse-set-region
        org-agenda
        org-self-insert-command
        projectile-switch-project
        selected-off
        smart-region
        ))
